services:
  keycloak_ai_summarize:
    image: quay.io/keycloak/keycloak:23.0.0
    command:
      - start-dev
      - --http-port=8180
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_ai_summarize
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: pass
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin1
      KEYCLOAK_FRONTEND_URL: http://localhost:8180
      KEYCLOAK_BASE_URL: http://localhost:8180/auth
    ports:
      - 8180:8180
    depends_on:
      - postgres_keycloak_ai_summarize
    networks:
      - keycloak_ai_summarize_dev_network

  postgres_keycloak_ai_summarize:
    image: postgres:16.1
    volumes:
      - pgdata_keycloak_ai_summarize:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: "exit 0"
    ports:
      - "30009:30009"
    networks:
      - keycloak_ai_summarize_dev_network
volumes:
  pgdata_keycloak_ai_summarize:
networks:
  keycloak_ai_summarize_dev_network:
    driver: bridge