import * as React from 'react';
import {useState} from 'react';
import {styled} from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Fab from '@mui/material/Fab';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';
import ListSubheader from '@mui/material/ListSubheader';
import KeyboardDoubleArrowRightIcon from '@mui/icons-material/KeyboardDoubleArrowRight';
import {SwitchAccessShortcutAdd} from "@mui/icons-material";
import {Drawer} from "@mui/material";


const messages = [
    {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
    },
    {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        id: 8,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        id: 9,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 10,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
];
const StyledFab = styled(Fab)(({theme, open}) => ({
    position: 'absolute',
    zIndex: 1,
    background: 'linear-gradient(to top left, rgba(242, 246, 255, 0.5), rgba(96, 46, 166, 1) 30%, rgba(96, 46, 166, 0))',
    left: open ? `calc(30% - ${theme.spacing(2)})` : 0,
    transition: theme.transitions.create(['left'], {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.enteringScreen,
    }),
}));

export default function SideBar() {
    const [isOpen, setIsOpen] = useState(false);

    const toggleDrawer = () => {
        setIsOpen(!isOpen);
    };

    return (
        <React.Fragment>
            <CssBaseline/>
            <Drawer
                variant="persistent"
                anchor="left"
                open={isOpen}
                sx={{
                    width: '30%',
                    flexShrink: 0,
                    '& .MuiDrawer-paper': {
                        width: '30%',
                        boxSizing: 'border-box',
                    },
                }}
            >
                <Typography variant="h5" gutterBottom component="div" sx={{p: 2, pb: 0}}>

                </Typography>
                <List sx={{mb: 2}}>
                    {messages.map(({id, primary, secondary}) => (
                        <React.Fragment key={id}>
                            {id === 1 && (
                                <ListSubheader sx={{bgcolor: 'background.paper'}}>
                                    Today
                                </ListSubheader>
                            )}
                            {id === 3 && (
                                <ListSubheader sx={{bgcolor: 'background.paper'}}>
                                    Yesterday
                                </ListSubheader>
                            )}
                            {id === 4 && (
                                <ListSubheader sx={{bgcolor: 'background.paper'}}>
                                    Latest
                                </ListSubheader>
                            )}

                            <ListItem button>
                                <ListItemText primary={primary} secondary={secondary}/>
                            </ListItem>
                        </React.Fragment>
                    ))}
                </List>
                <Toolbar sx={{
                    background: 'linear-gradient(to top left, rgba(242, 246, 255, 0 ), rgba(96, 46, 166, 0.9) 30%, rgba(96, 46, 166, 1))',
                    position: 'fixed', top: 'auto', bottom: 0, width: '30%', left: 0
                }}>
                    <IconButton color="inherit" aria-label="open drawer" onClick={toggleDrawer}>
                        <SwitchAccessShortcutAdd/>
                        Upgrade plan
                    </IconButton>
                </Toolbar>
            </Drawer>
            <StyledFab color="grey" open={isOpen}>
                <KeyboardDoubleArrowRightIcon fontSize={'large'} onClick={toggleDrawer}/>
            </StyledFab>
        </React.Fragment>
    );
}